### ISSUE TITLE
Bug:  last characters are missing in PDF document

### ISSUE THREAD

**Issue by Tabaluga** [koraycoding/paper-wallet#1]
Dear @koraylinux ,

thank you for your great application.

Today I noticed that the last characters of the category *Secret* are missing on all generated PDF documents:

- Close parenthesis at Secret
- The last character of the key

Thank you very much for your efforts.

Best regards

**Comment by expatjedi** [comment]
What's your operating system and what do you use for printing?

I checked the printed pdf files on windows 7, 10 and arch linux and all of them works without any problem.

May be your print settings cropping some characters?
